# This is a basic workflow to help you get started with Actions

name: Deployment

on:
  push:
    branches:
      - main
   

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production,staging
    steps:
      - name: deploy
        # ...deployment-specific steps
        run: echo Hello, world!  ${{ inputs.build_env_name }}
